### ISSUE TITLE
[BUG] Keeps Braking

### ISSUE THREAD

**Issue by BallisticOK** [GouveiaXS/angelicxs-FREE-VINscratch#2]
Sometime when doing the VINs it will sometimes not let the user in the car and then it just fully stops working

**Comment by GouveiaXS** [comment]
You are most likely using a key script in your server. There is known conflicts with key scripts. 
Assuming you are using qb-vehiclekeys this is how you can bypass it.
Add this at about line 282 in the client:
```TriggerEvent("vehiclekeys:client:SetOwner", GetVehicleNumberPlateText(MissionVehicle))```
If you use a different key system just replace the event above with the appropriate key giving event.

**Comment by Sully1796376** [comment]
am having this as well can u confirm were about i need to put this in my qb keys or your client

**Comment by GouveiaXS** [comment]
This need to go into the client of the VIN Scratch script.

**Comment by Sully1796376** [comment]
Also the lock picks don’t get removed from players when they lock pick the car

**Comment by GouveiaXS** [comment]
> Also the lock picks don’t get removed from players when they lock pick the car

Thank you for noting this, the callback was not correctly set up. It has been fixed in V1.2.2 (only the client side needs to be updated)

**Comment by Sully1796376** [comment]
I’ve added the key part in but the car still gets bugged out and u can’t get in to the car or lock pick it can you make it so you can select what keys you use in config

**Comment by GouveiaXS** [comment]
I looked and its because I gave you the wrong line number. It should be 292 which would look like this after the key portion.
```
ClearPedTasks(Player)
FreezeEntityPosition(Player, false)
RemoveAnimDict("anim@amb@clubhouse@tutorial@bkr_tut_ig3@")
SetVehicleDoorsLockedForAllPlayers(MissionVehicle, false)
local EndPoint = DropOff(MissionType)
CarAvailable = true
TriggerEvent("vehiclekeys:client:SetOwner", GetVehicleNumberPlateText(MissionVehicle))
if Config.CleanGetAway then
   TriggerServerEvent('angelicxs-FREE-VINscratch:Server:IsCoastClear',EndPoint)
end
```

This script is the _free_ version of my actual VIN scratching script  (https://angelicxs.tebex.io/package/5033558) and is feature complete. I will fix actual bugs reported with it (such as the lockpicks not being removed) but have no plans on putting in any further compatibility features. 
That is what the paid version contains, along with more indepth support.
